const actionTypes = {
  LOAD_BIKES: 'LOAD_BIKES',
  POST_BIKE: 'POST_BIKE',
  DELETE_BIKE: 'DELETE_BIKE',
  ADD_TO_FAVORITES: 'ADD_TO_FAVORITES',
  DELETE_FROM_FAVORITES: 'DELETE_FROM_FAVORITES',
  LOAD_IMAGE: 'LOAD_IMAGE',
  POST_IMAGE: 'POST_IMAGE',
  DELETE_IMAGE: 'DELETE_IMAGE',
};

export default actionTypes;
