// eslint-disable-next-line import/no-anonymous-default-export
export default {
  LOAD_BIKES: 'LOAD_BIKES',
  POST_BIKE: 'POST_BIKE',
  DELETE_BIKE: 'DELETE_BIKE',
  ADD_TO_FAVORITES: 'ADD_TO_FAVORITES',
  DELETE_FROM_FAVORITES: 'DELETE_FROM_FAVORITES',
  LOAD_IMAGE: 'LOAD_IMAGE',
  POST_IMAGE: 'POST_IMAGE',
  DELETE_IMAGE: 'DELETE_IMAGE',
  FAILED_TO_LOAD: 'FAILED_TO_LOAD',
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER'
};
